package enum

// ProjectSignal ...
type ProjectSignal int

const (
	// REPORTUPDATE ...
	REPORTUPDATE ProjectSignal = iota
	// PROJECTCOMPLETION ...
	PROJECTCOMPLETION
	// COMMENCEMENT ...
	COMMENCEMENT
)

// TaskSignal ...
type TaskSignal int

const (
	// ACCEPTANCE ...
	ACCEPTANCE TaskSignal = iota
	// REJECTION ...
	REJECTION
	// COMPLETION ...
	COMPLETION
)
